[global]
showWarningOnDirectExecution = true

[logger]
level = "debug"

[runner]
magicEnabled = true

[server]
folderWatchBlacklist = ['']

headless = true

liveSave = false

runOnSave = false

port = 8502

enableCORS = false

[browser]
serverAddress = "0.0.0.0"

gatherUsageStats = true

serverPort = 8502